spring:
  aop:
    proxy-target-class: false
  datasource:
    dynamic:
      primary: salescneter
      strict: false
      datasource:
        my:
          url: jdbc:mysql://1xxxx:3306/test?serverTimezone=Hongkong&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
          username: root
          password: xxxx
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
          hikari:
            max-lifetime: 30000
            minimum-idle: 3
            connection-test-query: SELECT 1
            maximum-pool-size: 10
        salescneter:
          url: jdbc:mysql://xxx:3306/center?serverTimezone=Hongkong&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
          username: root
          password: xxxx
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
          hikari:
            max-lifetime: 30000
            minimum-idle: 3
            connection-test-query: SELECT 1
            maximum-pool-size: 10
server:
  port: 8096

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml